create table customer (
	id INT,
	name VARCHAR(50),
	city VARCHAR(50),
	mobileNo INT,
	age INT
);

select * from customer;

select max(age) from customer;
select min(age) from customer;
select avg(age) from customer;

update customer set age = floor (18+(rand()*33))where age is null limit 120;
select * from customer;

select id from customer where age = 22;

insert into customer(id,name,city,mobileNo,age) values(1149,'abc','delhi',7765433,22);
insert into customer (id, name, city, mobileNo, age) values (1, 'Bernadene', 'Brighty', 55, 63);
insert into customer (id, name, city, mobileNo, age) values (2, 'Swen', 'Demeza', 22, 35);
insert into customer (id, name, city, mobileNo, age) values (3, 'Eba', 'Cayley', 25, 8);
insert into customer (id, name, city, mobileNo, age) values (4, 'Rosella', 'Dey', 29, 46);
insert into customer (id, name, city, mobileNo, age) values (5, 'Paulette', 'Allix', 85, 59);
insert into customer (id, name, city, mobileNo, age) values (6, 'Obie', 'Hullah', 1, 82);
insert into customer (id, name, city, mobileNo, age) values (7, 'Margaretha', 'Yanin', 26, 16);
insert into customer (id, name, city, mobileNo, age) values (8, 'Fredericka', 'Haliday', 15, 78);
insert into customer (id, name, city, mobileNo, age) values (9, 'Hillel', 'Dyerson', 3, 10);
insert into customer (id, name, city, mobileNo, age) values (10, 'Missie', 'Engledow', 67, 14);
insert into customer (id, name, city, mobileNo, age) values (11, 'Nickolaus', 'Berrycloth', 20, 44);
insert into customer (id, name, city, mobileNo, age) values (12, 'Domenico', 'Horwell', 97, 41);
insert into customer (id, name, city, mobileNo, age) values (13, 'Wendie', 'Ackland', 94, 94);
insert into customer (id, name, city, mobileNo, age) values (14, 'Teddie', 'Shillabeare', 86, 69);
insert into customer (id, name, city, mobileNo, age) values (15, 'Morie', 'Scranney', 20, 51);
insert into customer (id, name, city, mobileNo, age) values (16, 'Georas', 'Zoanetti', 96, 83);
insert into customer (id, name, city, mobileNo, age) values (17, 'Meier', 'Lengthorn', 68, 67);
insert into customer (id, name, city, mobileNo, age) values (18, 'Aliza', 'Karp', 30, 53);
insert into customer (id, name, city, mobileNo, age) values (19, 'Mirabel', 'Magee', 85, 45);
insert into customer (id, name, city, mobileNo, age) values (20, 'Gaylor', 'Isaq', 3, 19);
insert into customer (id, name, city, mobileNo, age) values (21, 'Lynnette', 'Ahmad', 24, 4);
insert into customer (id, name, city, mobileNo, age) values (22, 'Gerek', 'Papaminas', 53, 66);
insert into customer (id, name, city, mobileNo, age) values (23, 'Catlin', 'Matoshin', 95, 88);
insert into customer (id, name, city, mobileNo, age) values (24, 'Juliette', 'Vischi', 12, 9);
insert into customer (id, name, city, mobileNo, age) values (25, 'Carter', 'Magovern', 28, 57);
insert into customer (id, name, city, mobileNo, age) values (26, 'Creighton', 'Hoopper', 80, 93);
insert into customer (id, name, city, mobileNo, age) values (27, 'Nico', 'Dellenbroker', 6, 74);
insert into customer (id, name, city, mobileNo, age) values (28, 'Deloris', 'Bortoli', 48, 25);
insert into customer (id, name, city, mobileNo, age) values (29, 'Hilario', 'Haig', 91, 58);
insert into customer (id, name, city, mobileNo, age) values (30, 'Sven', 'Loy', 34, 67);
insert into customer (id, name, city, mobileNo, age) values (31, 'Christina', 'Crunkhurn', 98, 36);
insert into customer (id, name, city, mobileNo, age) values (32, 'Monique', 'MacCorley', 95, 88);
insert into customer (id, name, city, mobileNo, age) values (33, 'Katti', 'Maton', 60, 60);
insert into customer (id, name, city, mobileNo, age) values (34, 'Berna', 'Schuricht', 20, 23);
insert into customer (id, name, city, mobileNo, age) values (35, 'Price', 'Nann', 50, 64);
insert into customer (id, name, city, mobileNo, age) values (36, 'Adah', 'Taffie', 53, 31);
insert into customer (id, name, city, mobileNo, age) values (37, 'Rafael', 'O''Rudden', 90, 73);
insert into customer (id, name, city, mobileNo, age) values (38, 'Charmian', 'Harcombe', 54, 96);
insert into customer (id, name, city, mobileNo, age) values (39, 'Amitie', 'Lucio', 98, 19);
insert into customer (id, name, city, mobileNo, age) values (40, 'Orlan', 'Perroni', 2, 90);
insert into customer (id, name, city, mobileNo, age) values (41, 'Nertie', 'McCrae', 7, 5);
insert into customer (id, name, city, mobileNo, age) values (42, 'Jase', 'Roglieri', 18, 56);
insert into customer (id, name, city, mobileNo, age) values (43, 'Hayyim', 'Langwade', 82, 66);
insert into customer (id, name, city, mobileNo, age) values (44, 'Tierney', 'Sams', 60, 92);
insert into customer (id, name, city, mobileNo, age) values (45, 'Benoite', 'Soane', 35, 92);
insert into customer (id, name, city, mobileNo, age) values (46, 'Ira', 'Caldwall', 90, 4);
insert into customer (id, name, city, mobileNo, age) values (47, 'Madalena', 'O''Rafferty', 28, 74);
insert into customer (id, name, city, mobileNo, age) values (48, 'Winifred', 'Quinnette', 55, 35);
insert into customer (id, name, city, mobileNo, age) values (49, 'Smith', 'Darker', 63, 75);
insert into customer (id, name, city, mobileNo, age) values (50, 'Shep', 'Wipper', 24, 94);
insert into customer (id, name, city, mobileNo, age) values (51, 'Giacopo', 'Laity', 77, 4);
insert into customer (id, name, city, mobileNo, age) values (52, 'Fernande', 'Stickland', 47, 22);
insert into customer (id, name, city, mobileNo, age) values (53, 'Marinna', 'Frane', 23, 26);
insert into customer (id, name, city, mobileNo, age) values (54, 'Pincus', 'Ordelt', 29, 8);
insert into customer (id, name, city, mobileNo, age) values (55, 'Corty', 'Symones', 27, 69);
insert into customer (id, name, city, mobileNo, age) values (56, 'Marris', 'Axby', 97, 11);
insert into customer (id, name, city, mobileNo, age) values (57, 'Clemmie', 'McGrory', 51, 8);
insert into customer (id, name, city, mobileNo, age) values (58, 'Milicent', 'Zanetti', 25, 29);
insert into customer (id, name, city, mobileNo, age) values (59, 'Wilone', 'Bowdrey', 56, 22);
insert into customer (id, name, city, mobileNo, age) values (60, 'Legra', 'Molyneux', 37, 60);
insert into customer (id, name, city, mobileNo, age) values (61, 'Laurie', 'Bruton', 6, 65);
insert into customer (id, name, city, mobileNo, age) values (62, 'Harbert', 'Segeswoeth', 26, 40);
insert into customer (id, name, city, mobileNo, age) values (63, 'Deck', 'Rottery', 76, 13);
insert into customer (id, name, city, mobileNo, age) values (64, 'Daphne', 'Gimber', 45, 73);
insert into customer (id, name, city, mobileNo, age) values (65, 'Colly', 'Foreman', 2, 99);
insert into customer (id, name, city, mobileNo, age) values (66, 'Thaddeus', 'Vallantine', 89, 62);
insert into customer (id, name, city, mobileNo, age) values (67, 'Russ', 'Partrick', 61, 93);
insert into customer (id, name, city, mobileNo, age) values (68, 'Shurwood', 'Dunton', 52, 39);
insert into customer (id, name, city, mobileNo, age) values (69, 'Shayna', 'Tweedlie', 9, 8);
insert into customer (id, name, city, mobileNo, age) values (70, 'Kingston', 'Pilsworth', 100, 28);
insert into customer (id, name, city, mobileNo, age) values (71, 'Gwendolyn', 'Mation', 44, 64);
insert into customer (id, name, city, mobileNo, age) values (72, 'Carrissa', 'Genney', 33, 71);
insert into customer (id, name, city, mobileNo, age) values (73, 'Federica', 'Cockings', 47, 67);
insert into customer (id, name, city, mobileNo, age) values (74, 'Allard', 'Holyland', 2, 26);
insert into customer (id, name, city, mobileNo, age) values (75, 'Cornall', 'Leahey', 98, 20);
insert into customer (id, name, city, mobileNo, age) values (76, 'Lacie', 'Spilsted', 7, 87);
insert into customer (id, name, city, mobileNo, age) values (77, 'Isidro', 'Ruck', 54, 98);
insert into customer (id, name, city, mobileNo, age) values (78, 'Kiley', 'Aitchison', 69, 10);
insert into customer (id, name, city, mobileNo, age) values (79, 'Padriac', 'Cussen', 92, 19);
insert into customer (id, name, city, mobileNo, age) values (80, 'Donna', 'Mawman', 87, 8);
insert into customer (id, name, city, mobileNo, age) values (81, 'Christiano', 'Fawlks', 13, 33);
insert into customer (id, name, city, mobileNo, age) values (82, 'Nefen', 'Thody', 39, 77);
insert into customer (id, name, city, mobileNo, age) values (83, 'Cristiano', 'Florey', 71, 86);
insert into customer (id, name, city, mobileNo, age) values (84, 'Ivett', 'Boggas', 97, 5);
insert into customer (id, name, city, mobileNo, age) values (85, 'Rowen', 'Meates', 47, 42);
insert into customer (id, name, city, mobileNo, age) values (86, 'Niccolo', 'Kells', 18, 10);
insert into customer (id, name, city, mobileNo, age) values (87, 'Suzanne', 'Gynni', 33, 94);
insert into customer (id, name, city, mobileNo, age) values (88, 'Foster', 'Vispo', 11, 61);
insert into customer (id, name, city, mobileNo, age) values (89, 'Moishe', 'Deniset', 55, 15);
insert into customer (id, name, city, mobileNo, age) values (90, 'Dorita', 'Nieass', 6, 16);
insert into customer (id, name, city, mobileNo, age) values (91, 'Lindsey', 'Sebring', 63, 1);
insert into customer (id, name, city, mobileNo, age) values (92, 'Mendie', 'Duell', 57, 88);
insert into customer (id, name, city, mobileNo, age) values (93, 'Sheree', 'Wherrit', 3, 23);
insert into customer (id, name, city, mobileNo, age) values (94, 'Dalia', 'Padilla', 7, 27);
insert into customer (id, name, city, mobileNo, age) values (95, 'Welsh', 'Epp', 85, 85);
insert into customer (id, name, city, mobileNo, age) values (96, 'Annaliese', 'Dracksford', 5, 24);
insert into customer (id, name, city, mobileNo, age) values (97, 'Orella', 'Bartosik', 21, 65);
insert into customer (id, name, city, mobileNo, age) values (98, 'Melonie', 'Toombs', 39, 81);
insert into customer (id, name, city, mobileNo, age) values (99, 'Sileas', 'Petrovykh', 16, 5);
insert into customer (id, name, city, mobileNo, age) values (100, 'Doro', 'Roby', 15, 14);
insert into customer (id, name, city, mobileNo, age) values (101, 'Lonee', 'Stopper', 69, 61);
insert into customer (id, name, city, mobileNo, age) values (102, 'Eilis', 'Ginglell', 24, 82);
insert into customer (id, name, city, mobileNo, age) values (103, 'Hale', 'Sturdgess', 34, 87);
insert into customer (id, name, city, mobileNo, age) values (104, 'Dun', 'Beet', 52, 57);
insert into customer (id, name, city, mobileNo, age) values (105, 'Donny', 'Froggatt', 23, 60);
insert into customer (id, name, city, mobileNo, age) values (106, 'Brooke', 'Tallon', 66, 69);
insert into customer (id, name, city, mobileNo, age) values (107, 'Licha', 'McIlraith', 99, 32);
insert into customer (id, name, city, mobileNo, age) values (108, 'Avril', 'Huston', 94, 25);
insert into customer (id, name, city, mobileNo, age) values (109, 'Barbey', 'Crowley', 2, 43);
insert into customer (id, name, city, mobileNo, age) values (110, 'Nicola', 'Passingham', 82, 21);
insert into customer (id, name, city, mobileNo, age) values (111, 'Dulci', 'Peascod', 13, 49);
insert into customer (id, name, city, mobileNo, age) values (112, 'Marley', 'Main', 5, 83);
insert into customer (id, name, city, mobileNo, age) values (113, 'Delcine', 'Shills', 87, 65);
insert into customer (id, name, city, mobileNo, age) values (114, 'Camellia', 'Crompton', 53, 17);
insert into customer (id, name, city, mobileNo, age) values (115, 'Cordelie', 'Sandey', 68, 39);
insert into customer (id, name, city, mobileNo, age) values (116, 'Bank', 'Trimmill', 55, 78);
insert into customer (id, name, city, mobileNo, age) values (117, 'Sebastien', 'Lieber', 85, 50);
insert into customer (id, name, city, mobileNo, age) values (118, 'Giulia', 'Tremmil', 58, 19);
insert into customer (id, name, city, mobileNo, age) values (119, 'Mina', 'Warne', 9, 89);
insert into customer (id, name, city, mobileNo, age) values (120, 'Thaine', 'Andreas', 39, 81);
