create table restaurant (
	registerno INT,
	name VARCHAR(50),
	city VARCHAR(50),
	area VARCHAR(50)
);
insert into restaurant (registerno, name, city, area) values (1, 'wteather0', 'Beiwa', 'Oliveira');
insert into restaurant (registerno, name, city, area) values (2, 'cmicklewright1', 'Mabini', 'La Libertad');
insert into restaurant (registerno, name, city, area) values (3, 'aoconnolly2', 'Changsha', 'MÃ¶rrum');
insert into restaurant (registerno, name, city, area) values (4, 'wklamman3', 'Ytterby', 'SharÄ«fÄbÄd');
insert into restaurant (registerno, name, city, area) values (5, 'ipedroni4', 'Enshi', 'Kuzhuping');
insert into restaurant (registerno, name, city, area) values (6, 'dgrandison5', 'Saga-shi', 'Polloc');
insert into restaurant (registerno, name, city, area) values (7, 'drayne6', 'Palmas', 'Pinggang');
insert into restaurant (registerno, name, city, area) values (8, 'kolrenshaw7', 'Aracaju', 'Abelheira');
insert into restaurant (registerno, name, city, area) values (9, 'jwaddam8', 'Ndano', 'Cheremnoye');
insert into restaurant (registerno, name, city, area) values (10, 'dcoleman9', 'Yanghu', 'Gjinkar');
insert into restaurant (registerno, name, city, area) values (11, 'twormleightona', 'Coris', 'PucÃ³n');
insert into restaurant (registerno, name, city, area) values (12, 'caudrittb', 'GÃ¶teborg', 'Tifni');
insert into restaurant (registerno, name, city, area) values (13, 'mdmtrovicc', 'Wierzchucino', 'Citarik');
insert into restaurant (registerno, name, city, area) values (14, 'tsharpleyd', 'Louveira', 'Huaqiao');
insert into restaurant (registerno, name, city, area) values (15, 'hstrongmane', 'MaracanaÃº', 'Yuncheng');
insert into restaurant (registerno, name, city, area) values (16, 'tmaffinf', 'Kharkhorin', 'Yuqian');
insert into restaurant (registerno, name, city, area) values (17, 'mcloneyg', 'Tsaghveri', 'Xinan');
insert into restaurant (registerno, name, city, area) values (18, 'ascullinh', 'Kotabaru', 'El Cobre');
insert into restaurant (registerno, name, city, area) values (19, 'bdominicki', 'Sumberejo', 'Temuji');
insert into restaurant (registerno, name, city, area) values (20, 'hvinauj', 'Shiwan', 'Horodyshche');
insert into restaurant (registerno, name, city, area) values (21, 'jtowsiek', 'Rafaela', 'Pilchowice');
insert into restaurant (registerno, name, city, area) values (22, 'mblucherl', 'Gesing', 'Parungjawa');
insert into restaurant (registerno, name, city, area) values (23, 'jfouldsm', 'Hassi Berkane', 'Vredenburg');
insert into restaurant (registerno, name, city, area) values (24, 'sbrigshawn', 'Krasnoturâ€™insk', 'KhalkhÄl');
insert into restaurant (registerno, name, city, area) values (25, 'mbullivento', 'Banjar Taro Kelod', 'HÃ¶drÃ¶gÃ¶');
insert into restaurant (registerno, name, city, area) values (26, 'ntrammelp', 'Pule', 'Supu');
insert into restaurant (registerno, name, city, area) values (27, 'egallandreq', 'Petiga', 'Straszydle');
insert into restaurant (registerno, name, city, area) values (28, 'lbriztmanr', 'Martapura', 'Kamwenge');
insert into restaurant (registerno, name, city, area) values (29, 'asargersons', 'Dawung', 'Zhangzhu');
insert into restaurant (registerno, name, city, area) values (30, 'acawthornt', 'MompÃ³s', 'Yurovka');
insert into restaurant (registerno, name, city, area) values (31, 'jraunu', 'Klirou', 'Bintawan');
insert into restaurant (registerno, name, city, area) values (32, 'tkrugmannv', 'Gareba', 'Roissy Charles-de-Gaulle');
insert into restaurant (registerno, name, city, area) values (33, 'rbourgourw', 'Itoman', 'Senangkhanikhom');
insert into restaurant (registerno, name, city, area) values (34, 'sfyallx', 'Dorogobuzh', 'Yuetang');
insert into restaurant (registerno, name, city, area) values (35, 'mjosuweity', 'BÅ™ezovÃ¡', 'Kitwe');
insert into restaurant (registerno, name, city, area) values (36, 'hbutenz', 'Touho', 'BÄƒlÅ£i');
insert into restaurant (registerno, name, city, area) values (37, 'gbaily10', 'Popil''nya', 'Chicacao');
insert into restaurant (registerno, name, city, area) values (38, 'ralsford11', 'HÃ¤gersten', 'Miaoya');
insert into restaurant (registerno, name, city, area) values (39, 'qhardaker12', 'Chixi', 'Gotovlje');
insert into restaurant (registerno, name, city, area) values (40, 'ibrownlee13', 'Zelenokumsk', 'Imbituba');
insert into restaurant (registerno, name, city, area) values (41, 'mbaldry14', 'PÃ©rigny', 'Mariquita');
insert into restaurant (registerno, name, city, area) values (42, 'vpallas15', 'LidingÃ¶', 'ZaÅ‚uski');
insert into restaurant (registerno, name, city, area) values (43, 'hcolvill16', 'Fandriana', 'Jayanca');
insert into restaurant (registerno, name, city, area) values (44, 'wfanton17', 'Malo', 'Banatsko Veliko Selo');
insert into restaurant (registerno, name, city, area) values (45, 'gpierse18', 'Aotou', 'Pilzno');
insert into restaurant (registerno, name, city, area) values (46, 'eanchor19', 'Vitebsk', 'Kulutan');
insert into restaurant (registerno, name, city, area) values (47, 'averrill1a', 'BaborÃ³w', 'Bojongsari');
insert into restaurant (registerno, name, city, area) values (48, 'kbruneton1b', 'Tiedonglu', 'Gubu');
insert into restaurant (registerno, name, city, area) values (49, 'drowlett1c', 'Manadas', 'BÃ¡nica');
insert into restaurant (registerno, name, city, area) values (50, 'kenrdigo1d', 'Suvorovskaya', 'Krajenka');
insert into restaurant (registerno, name, city, area) values (51, 'traymen1e', 'Shigou', 'Los Cerrillos');
insert into restaurant (registerno, name, city, area) values (52, 'vraffles1f', 'Sukamaju', 'SÃ£o Leopoldo');
insert into restaurant (registerno, name, city, area) values (53, 'gcanas1g', 'Nueva Guadalupe', 'ShakÄ«so');
insert into restaurant (registerno, name, city, area) values (54, 'bturbayne1h', 'Heshan', 'Sundbyberg');
insert into restaurant (registerno, name, city, area) values (55, 'dscrymgeour1i', 'Licupis', 'Bulacan');
insert into restaurant (registerno, name, city, area) values (56, 'cmarston1j', 'Chkalov', 'Riit');
insert into restaurant (registerno, name, city, area) values (57, 'wwiltshaw1k', 'Bethlehem', 'Xinjie');
insert into restaurant (registerno, name, city, area) values (58, 'mmegany1l', 'Malalag', 'Shanhou');
insert into restaurant (registerno, name, city, area) values (59, 'ecoombs1m', 'Bijeli', 'Beigao');
insert into restaurant (registerno, name, city, area) values (60, 'gdederich1n', 'Nanling', 'Young America');
insert into restaurant (registerno, name, city, area) values (61, 'gpryde1o', 'Libertad', 'Baoshan');
insert into restaurant (registerno, name, city, area) values (62, 'dmattia1p', 'Jiefu', 'Gupakan');
insert into restaurant (registerno, name, city, area) values (63, 'bnewns1q', 'Gondomar', 'Tonjongsari');
insert into restaurant (registerno, name, city, area) values (64, 'dgatrell1r', 'Braga', 'Mesa');
insert into restaurant (registerno, name, city, area) values (65, 'kmatches1s', 'IbaguÃ©', 'Stockholm');
insert into restaurant (registerno, name, city, area) values (66, 'ogalbraeth1t', 'La Troncal', 'Leping');
insert into restaurant (registerno, name, city, area) values (67, 'iokenfold1u', 'Kladanj', 'Palopat');
insert into restaurant (registerno, name, city, area) values (68, 'svalenssmith1v', 'Roczyny', 'Boyang');
insert into restaurant (registerno, name, city, area) values (69, 'llegge1w', 'Columbia', 'Batakte');
insert into restaurant (registerno, name, city, area) values (70, 'mbaldrick1x', 'Tanenofunan', 'Antequera');
insert into restaurant (registerno, name, city, area) values (71, 'vcantle1y', 'Tha Maka', 'CherÃ«mushki');
insert into restaurant (registerno, name, city, area) values (72, 'kdurward1z', 'Baruchowo', 'MÄ«zan TeferÄ«');
insert into restaurant (registerno, name, city, area) values (73, 'tgrafom20', 'Boljevac', 'Carmo do ParanaÃ­ba');
insert into restaurant (registerno, name, city, area) values (74, 'sdowears21', 'Aniva', 'Anfeng');
insert into restaurant (registerno, name, city, area) values (75, 'jlenchenko22', 'Ilâ€™inskiy', 'Metz');
insert into restaurant (registerno, name, city, area) values (76, 'emattheeuw23', 'Xinghua', 'Pilcaniyeu');
insert into restaurant (registerno, name, city, area) values (77, 'skohen24', 'Jishi', 'Xiushi');
insert into restaurant (registerno, name, city, area) values (78, 'dstoffels25', 'Zhangcunping', 'Bishan');
insert into restaurant (registerno, name, city, area) values (79, 'rricard26', 'Vyksa', 'Tena');
insert into restaurant (registerno, name, city, area) values (80, 'emoakes27', 'Shicheng', 'Krajan Gajahmati');
insert into restaurant (registerno, name, city, area) values (81, 'lpleavin28', 'Shimada', 'Dushi');
insert into restaurant (registerno, name, city, area) values (82, 'mgauford29', 'Kyaka', 'Dayou');
insert into restaurant (registerno, name, city, area) values (83, 'ybarke2a', 'Furmanov', 'Pointe-Ã -Pitre');
insert into restaurant (registerno, name, city, area) values (84, 'fhabershon2b', 'FareydÅ«nshahr', 'Kajan');
insert into restaurant (registerno, name, city, area) values (85, 'ldarwen2c', 'Saint Helier', 'Netolice');
insert into restaurant (registerno, name, city, area) values (86, 'achudleigh2d', 'Nagasari', 'Pimian');
insert into restaurant (registerno, name, city, area) values (87, 'battiwill2e', 'El Soberbio', 'Sulang Tengah');
insert into restaurant (registerno, name, city, area) values (88, 'fcraker2f', 'KrujÃ«', 'Utsjoki');
insert into restaurant (registerno, name, city, area) values (89, 'trigmand2g', 'Amucao', 'Sandefjord');
insert into restaurant (registerno, name, city, area) values (90, 'lwooler2h', 'SuchaÅ„', 'Nechanice');
insert into restaurant (registerno, name, city, area) values (91, 'bmuzzollo2i', 'Issa', 'ÄŒoka');
insert into restaurant (registerno, name, city, area) values (92, 'gmargram2j', 'Cibeunying', 'Al á¸¨affah');
insert into restaurant (registerno, name, city, area) values (93, 'choofe2k', 'Baoâ€™an', 'Huangmao');
insert into restaurant (registerno, name, city, area) values (94, 'woshavlan2l', 'MalanÃ³w', 'Muramatsu');
insert into restaurant (registerno, name, city, area) values (95, 'mpaniman2m', 'Giedlarowa', 'Vryburg');
insert into restaurant (registerno, name, city, area) values (96, 'dmillson2n', 'MakrychÃ³ri', 'Biankouma');
insert into restaurant (registerno, name, city, area) values (97, 'bjakoubek2o', 'Heshi', 'Las Vegas');
insert into restaurant (registerno, name, city, area) values (98, 'ekalaher2p', 'Cotabambas', 'Kvasy');
insert into restaurant (registerno, name, city, area) values (99, 'lwaddy2q', 'Yuanda', 'Sousa');
insert into restaurant (registerno, name, city, area) values (100, 'jstiller2r', 'Segoro', 'Basa');
